### ISSUE TITLE
juiceResources is loading resources from disk when {url:...} value is provided

### ISSUE THREAD

**Issue by DinisCruz** [Automattic/juice#104]
We are using juice as part of our QA tests, and the new change from ```juiceContent``` to ```juiceResources``` is (I think) introducing more changes than just the name

Here is my test (written in coffee-script)

```coffee
  juice    = require('juice')
  cheerio = require('cheerio')

  check_Generic_Footer_Css = (html, baseUrl, next)->
    juice.juiceResources html, { url: baseUrl}, (err, cssHtml)->
      $css = cheerio.load(cssHtml)
      footer_Attr = $css('#footer #si-logo').attr()
      footer_Attr.assert_Is { id: 'si-logo', style: 'background: url(../assets/logos/logos.png) no-repeat; background-position: 0px -43px; height: 50px; width: 160px; margin: 0 auto;' }
      items = extract_Style_Data(footer_Attr.style)
      items['background'].assert_Is('url(../assets/logos/logos.jpg) no-repeat' )
      next()
```

What is happening is that I was using the ```juiceContent``` to create the html+css content, which was then feed to cheerio so that I could check for the correct mapping of our css.

The key of that function was to load the 'resources' from the live website (running on a local port) and it worked perfectly with ```juiceContent```

But with the latest version and ```juiceResources``` I now get the error:

```ssh

Error: ENOENT, no such file or directory '/Users/diniscruz/GitHub_REPOS/TM_4_0_QA/static/assets/favicons/apple-touch-icon-57x57.png'
  at Object.fs.openSync (fs.js:438:18)
  at Object.fs.readFileSync (fs.js:289:15)
  at Object.util.getInlineFileContents (/Users/diniscruz/GitHub_REPOS/TM_4_0_QA/node_modules/juice/node_modules/web-resource-inliner/src/util.js:98:17)
  at Object.util.getTextReplacement (/Users/diniscruz/GitHub_REPOS/TM_4_0_QA/node_modules/juice/node_modules/web-resource-inliner/src/util.js:109:30)
  at Object.replaceLink (/Users/diniscruz/GitHub_REPOS/TM_4_0_QA/node_modules/juice/node_modules/web-resource-inliner/src/html.js:41:16)
  at /Users/diniscruz/GitHub_REPOS/TM_4_0_QA/node_modules/async/lib/async.js:570:21
  at /Users/diniscruz/GitHub_REPOS/TM_4_0_QA/node_modules/async/lib/async.js:249:17
  at /Users/diniscruz/GitHub_REPOS/TM_4_0_QA/node_modules/async/lib/async.js:125:13
  at Array.forEach (native)
  at _each (/Users/diniscruz/GitHub_REPOS/TM_4_0_QA/node_modules/async/lib/async.js:46:24)
  at async.each (/Users/diniscruz/GitHub_REPOS/TM_4_0_QA/node_modules/async/lib/async.js:124:9)
  at _asyncMap (/Users/diniscruz/GitHub_REPOS/TM_4_0_QA/node_modules/async/lib/async.js:248:13)
  at Object.map (/Users/diniscruz/GitHub_REPOS/TM_4_0_QA/node_modules/async/lib/async.js:219:23)
  at _parallel (/Users/diniscruz/GitHub_REPOS/TM_4_0_QA/node_modules/async/lib/async.js:568:20)
  at Object.async.parallel (/Users/diniscruz/GitHub_REPOS/TM_4_0_QA/node_modules/async/lib/async.js:598:9)
  at Object.module.exports [as html] (/Users/diniscruz/GitHub_REPOS/TM_4_0_QA/node_modules/juice/node_modules/web-resource-inliner/src/html.js:144:11)
  at Object.exports.inlineExternal (/Users/diniscruz/GitHub_REPOS/TM_4_0_QA/node_modules/juice/lib/utils.js:145:10)
  at Function.juiceResources (/Users/diniscruz/GitHub_REPOS/TM_4_0_QA/node_modules/juice/lib/juice.js:188:9)
  at check_Generic_Footer_Css (/Users/diniscruz/GitHub_REPOS/TM_4_0_QA/tests/jade/pages-anonymous.test.coffee:63:11)
  at /Users/diniscruz/GitHub_REPOS/TM_4_0_QA/tests/jade/pages-anonymous.test.coffee:95:7
```

which means that ```juiceResources``` is trying to load the resources from the local disk and not from the provided url.

So what could be the problem here? Is it that the ```juice.juiceResources html, { url: baseUrl}, (err, cssHtml)``` is not correctly setting the url to fetch the resources?

For reference here is the travis tests that started to fail due to the function rename: https://travis-ci.org/TeamMentor/TM_4_0_QA#L1219

**Comment by jrit** [comment]
The `url` option was removed from that context because the process of pulling in external resources is now delegated to https://github.com/jrit/web-resource-inliner - there is an option named `relativeTo` on there that I think would resolve your issue. You would pass that option as `{ webResources: { relativeTo: url } }` if I understand the issue. If it turns out to be failing still we can open an issue on the inliner. 

It might be useful if we update juice to pass the old `url` option by default to the inliner option to support backwards compatibility better.

**Comment by tekgirl77** [comment]
Hi @jrit, I have tried your proposed solution and I am still getting the exact same error that @DinisCruz posted above; the juiceResources method seems to be prepending the cwd onto the relative path.  

```coffeescript
  jade.login_A
![screen shot 2015-03-18 at 11 52 58 am](https://cloud.githubusercontent.com/assets/6649463/6715638/66a48f4c-cd65-11e4-90b7-310e74912699.png)
s_User ->
      jade.page_User_Main (html, $)->
        juice = require('juice')
        cheerio = require('cheerio')
        baseUrl = page.tm_Server;
        juiceOptions = { webResources: { relativeTo: baseUrl }}
        #juiceOptions = {url: baseUrl}
        log "cwd is: " + process.cwd()
        juice.juiceResources html, juiceOptions, (err, cssHtml)->
          throw (err) if err
          $css = cheerio.load(cssHtml)
          attributes = $css('.input-group-btn').attr()
          attributes.assert_Is { class: 'input-group-btn', style: 'display: table-cell; vertical-align: bottom;' }
```



![screen shot 2015-03-18 at 11 56 23 am](https://cloud.githubusercontent.com/assets/6649463/6715706/dfaeda1e-cd65-11e4-9c41-cf8c9cfc29c9.png)



I see that you added legacy support for the options.url parameter, which I also tried, but it did not pick up the URL at all in that scenario.



![screen shot 2015-03-18 at 11 54 30 am](https://cloud.githubusercontent.com/assets/6649463/6715680/ac1cda52-cd65-11e4-8573-d12a2ac8a03f.png)


Please let me know if I am missing something??

Thanks!

**Comment by jrit** [comment]
@rauchg has not published a release that includes the fix yet, could that be the issue?

**Comment by tekgirl77** [comment]
Thanks for the quick response @jrit :) 

Looks like his changes were merged into master w/ the latest commit:
https://github.com/Automattic/juice/commit/ee5ef99e57f90e81ff403ede91e77b32dbb2e0f4 

I double checked and we are using juice v.1.0.0 as well.

**Comment by jrit** [comment]
Oh, I really have my dates mixed up. I think the fix you are looking for might be in the pending https://github.com/Automattic/juice/pull/107/files though, which I'm hoping will be a 1.0.1 soon. Would you mind validating against that version?

**Comment by tekgirl77** [comment]
haha sure I would be happy to!  Let me know when it is ready for validation.

**Comment by parshap** [comment]
It's ready now - you just need to do

```
npm install git@github.com:jrit/juice.git#cheerio-node-12
```

**Comment by tekgirl77** [comment]
Thanks @parshap, this command worked for me:
$ npm install jrit/juice.git#cheerio-node-12


It is skipping files which do exist at the relative path, and also throwing a parsing error; both of these juiceOptions.url and juiceOptions.webResources methods throw the exact same error:

``` Coffeescript 
jade.login_As_User ->
      jade.page_User_Main (html, $)->
        juice = require('juice')
        cheerio = require('cheerio')
        baseUrl = page.tm_Server;
        juiceOptions = { webResources: { relativeTo: baseUrl }}
        #juiceOptions = {url: baseUrl}
        juice.juiceResources html, juiceOptions, (err, cssHtml)->
          throw (err) if err
          $css = cheerio.load(cssHtml)
          attributes = $css('.input-group-btn').attr()
          attributes.assert_Is { class: 'input-group-btn', style: 'display: table-cell; vertical-align: bottom;' }
```



![screen shot 2015-03-18 at 3 29 45 pm](https://cloud.githubusercontent.com/assets/6649463/6719884/b338d746-cd83-11e4-97bf-0f3553e1e91a.png)
