### ISSUE TITLE
Improve "Error: Local file not found" message

### ISSUE THREAD

**Issue by binarykitchen** [Automattic/juice#108]
When migrating from v0.5 to v1.0 I got that error message when calling `juiceResources()` and have no idea what's wrong here.

Any chance this error message could tell a bit more? What local file it is referring to?

Basically I am figuring out how to migrate from `juice.juiceContent(html, options, cb)` to `juice.juiceResources(html, options, cb)` ...

**Comment by jrit** [comment]
Yeah, including the file path with that error is a good idea.

**Comment by jrit** [comment]
@binarykitchen I may need a test case as I get an error like `Error: ENOENT, no such file or directory 'C:\not-a-file.css'`

**Comment by binarykitchen** [comment]
Can't you just add the file path in the error message for now? That should be good enough.

Really cannot give you a test case because I have no idea where this error is coming from (and my code is too messy/deeply nested to isolate the issue, grins).

**Comment by jrit** [comment]
The error already includes the file path in my tests, as noted in my comment. The lack of the path in your error is what I'm not sure about. I've added a related issue here that should resolve this https://github.com/jrit/web-resource-inliner/issues/1 when done.

**Comment by binarykitchen** [comment]
Okay, I had a look and extracted you the variables for reproduction in this gist
https://gist.github.com/binarykitchen/f4f72c76a500f17e797c

Basically I am just calling `juiceResources()` with these three variables like that:

```js
juice.juiceResources(html, options, callback)
```

**Comment by jrit** [comment]
I believe the PR I have open fixes this @binarykitchen - I ran your actual gist through juice after updating.

**Comment by binarykitchen** [comment]
Ah, what was it @jrit then?
