### ISSUE TITLE
CLI does not work as advertised

### ISSUE THREAD

**Issue by adamlundrigan** [Automattic/juice#111]
```
$ bin/juice --help

  Usage: juice input.html output.html

  Options:

    -h, --help     output usage information
    -V, --version  output the version number
```

The implementation of the CLI uses [`juice()`](https://github.com/Automattic/juice/blob/master/bin/juice#L19) instead of `juice.juiceFile()`, resulting in the filename being processed instead of the contents of that filename.

**Comment by jrit** [comment]
closing as resolved by #112
