### ISSUE TITLE
Make it clear that juice doesn't support <link> tags

### ISSUE THREAD

**Issue by alexturpin** [Automattic/juice#113]
Hey guys,

Perhaps it should be made clear that juice doesn't support <link> tags anymore in the latest version. I upgraded, and wondering why my stuff wasn't working, I traced back the code all the way to the part that finds the CSS, only to discover it was only looking at <style> tags. I then did a global search for "link" to find the relevant History.md changes. Perhaps the documentation should be made clear to reflect this, as it still has some references to <link> tags.

Cheers

**Comment by jrit** [comment]
I'm not quite sure what you mean. `juice.juiceResources(html, options, callback)` and `juice.juiceFile(filePath, options, callback)` both should fetch external resources, as is noted in the readme. Is there something about the readme that isn't clear or is there a bug with a particular function that should be looked at? Several of the function signatures were changed in the V1 release.

**Comment by alexturpin** [comment]
Ahh you are quite right of course, I had been using `juiceDocument` but it is as clear as day on the docs: 

>Does not fetch remote resources.

My apologies, this issue doesn't exist.
