### ISSUE TITLE
[Question/Suggestion] - Command line processing

### ISSUE THREAD

**Issue by scottblair** [Automattic/juice#121]
I installed Juice through npm globally using npm install juice -g

Is it possible to run a command line action that would output an inlined file?

For example:
juice index.html > index-inlined.html

I'm trying to find a solution that will allow rapid email develop through CodeKit that doesn't require an install of dependencies for every email produced. I'm sometimes doing these 4-5x per day.

Thanks for your feedback!
Scott

**Comment by parshap** [comment]
Yes. Juice already installs a command line tool named `juice`. 

```
$ juice --help

  Usage: juice input.html output.html

  Options:

    -h, --help     output usage information
    -V, --version  output the version number
```

Try it out and let us know if it doesn't work as expected.

**Comment by scottblair** [comment]
When I run any commands for juice (after install), I get the following error message back:

env: node\r: No such file or directory

**Comment by parshap** [comment]
It looks like the `bin/juice.js` file published to npm has `CRLF` line endings (instead of just `LF`). This is not checked into git (as git normalizes endings to `LF`), so no commit is required, we just need to publish a new version with line endings fixed in the file. This would fix #118 as well. /cc @jrit

**Comment by scottblair** [comment]
I'll check for the the new version for this and retest it. Thank you for the response and assistance.

**Comment by parshap** [comment]
@scottblair you can also fix this locally temporarily by opening up the `bin/juice.js` file and fixing the line endings. You can do this using `vim` by opening the file (`vi bin/juice.js`) and entering `:set fileformat=unix` then saving and closing (`:wq`).

**Comment by jrit** [comment]
Just published a 1.1.1 to npm after fixing line endings locally. Guess there is a longstanding issue/conflict between line normalization on Windows git and npm publish - https://github.com/npm/npm/issues/2097

**Comment by scottblair** [comment]
I was initially having some permission issues overriding the file, and found I needed to edit the actual file instead of the symbolic link. /lib/node_modules/juice/bin/

I also needed to run VIM in sudo mode to give me the permissions to override the file. 

Thanks for the update too guys! :)
Scott

**Comment by scottblair** [comment]
Ok, it does run now... so the initial is resolved.
However... I'm getting an error that's tied to cssom. 

`/usr/local/lib/node_modules/juice/node_modules/cssom/lib/parse.js:58
		throw error;
		      ^
Error: Unexpected } (line 90, char 35)
    at parseError (/usr/local/lib/node_modules/juice/node_modules/cssom/lib/parse.js:54:15)
    at Object.parse (/usr/local/lib/node_modules/juice/node_modules/cssom/lib/parse.js:325:7)
    at Object.exports.parseCSS (/usr/local/lib/node_modules/juice/lib/utils.js:58:21)
    at inlineDocument (/usr/local/lib/node_modules/juice/lib/juice.js:72:21)
    at juiceDocument (/usr/local/lib/node_modules/juice/lib/juice.js:286:3)
    at onInline (/usr/local/lib/node_modules/juice/lib/juice.js:299:5)
    at /usr/local/lib/node_modules/juice/node_modules/web-resource-inliner/src/html.js:153:9
    at /usr/local/lib/node_modules/juice/node_modules/web-resource-inliner/node_modules/async/lib/async.js:254:17
    at done (/usr/local/lib/node_modules/juice/node_modules/web-resource-inliner/node_modules/async/lib/async.js:135:19)
    at /usr/local/lib/node_modules/juice/node_modules/web-resource-inliner/node_modules/async/lib/async.js:32:16`
