### ISSUE TITLE
Validation fails because juice pulls of trailing slash in my meta tag

### ISSUE THREAD

**Issue by sroberson** [Automattic/juice#122]
We're coding email templates whose doctype is XHTML 1.0 Transitional. This doctype requires closed tags, but my juiced html files have the closing tags removed.  Is there a way to stop this?  I don't see any options that describe this.

**Comment by jrit** [comment]
I think #109 would fix this, we were just waiting on tests and documentation to support the PR.

**Comment by gunnx** [comment]
+1
