### ISSUE TITLE
Double curly brackets enough to prevent publishing of email templates 

### ISSUE THREAD

**Issue by TKais** [Automattic/juice#123]
We use Juice2 to parse the CSS in email templates. But recently we've had some customers upload templates that contained two closing curly brackets '}}' instead of one. This was enough to prevent publishing the templates and moving forward, even though most browsers would've just ignored it

**Comment by parshap** [comment]
The repository for juice2 is here: https://github.com/andrewrk/juice

I suggest migrating back to juice, which has been more recently maintained and should have parity with juice2. If you are still having an issue can you provide an example?

**Comment by jrit** [comment]
There is a test case to cover the string `<p>Dear {{ $person->user->firstname }},</p>` so I'm going to close this.
