### ISSUE TITLE
[Docs] What is the correct way to include fonts?

### ISSUE THREAD

**Issue by rbhalla** [Automattic/juice#132]
Regardless of whether I use the resource-inliner or just a style tag, all font declarations get removed.

Since all my css comes from files, I tried only having the fonts in a style tag in the html file, but this seemed to be removed unless I set `removeStyleTags` to false, which of course meant all other styles that has been imported from files also remained in the head in a style tag.

What is the correct way to do this?

**Comment by jrit** [comment]
Personally, I wrap font declarations in a media query like `@media all { ... fonts here ... }` and then use `preserveMediaQueries`. I'm pretty sure there are no mail clients that can understand font declarations but not media queries, but could be wrong. In any case, this seems like it would be a common scenario and my way is somewhat of a workaround as well as not documented.

**Comment by rbhalla** [comment]
Ahh clever, that does work thanks.

What are the repercussions of preserving media queries otherwise? Since it defaults to false I'm assuming there are some things that I should be aware of before enabling it maybe?

**Comment by jrit** [comment]
I'm not aware there are repercussions. False is the default mostly for historical reasons. It does seem like an odd default now.

**Comment by rbhalla** [comment]
Ok great, thanks for your help!

**Comment by jrit** [comment]
Reopening this issue as a marker to improve documentation around this use case.

**Comment by jonscottclark** [comment]
The only problem with the `@media all` workaround is when you're using a service like Google Fonts, where you need to request an external resource. I use their `<link>` method, and then the resulting CSS gets inlined to a style tag by `juice`. Of course, if I have `removeStyleTags: true`, which is a setting I generally want to have on, then they get blasted away. I could just copy the resulting CSS and drop that in to the `@media all` query but the font resource returned by Google fonts is, for example, `http://fonts.gstatic.com/s/opensans/v13/k3k702ZOKiLJc3WVjuplzInF5uFdDttMLvmWuJdhhgs.ttf`, and is different for each font weight; so if I wanted to add a different weight, or a different font, I'd need to re-inline my file with `removeStyleTags` temporarily off, get the source, then drop that into a media query so it sticks.

Yeah, in the whole scheme of things it's still way easier than it was in years past, and this module is awesome and helps eliminate so many headaches, but I think the **tl:dr;** is that it should be safe to preserve any `@font-face` declaration that gets encountered, in the same manner as preserving media queries. In the meantime I'll drop in the raw CSS that Google Fonts sends back to me. Thanks for the tip, @jrit !

**Comment by jrit** [comment]
If you don't want to inline a `<link>` you can add the attribute `data-inline-ignore` like `<link href="..." data-inline-ignore >`. This is documented here https://www.npmjs.com/package/web-resource-inliner

The issue with Google fonts is sort of complicated by the fact that it returns different CSS depending on the user-agent that makes the request.

I totally get what you are saying though, @font-face is another thing like @media that can't be inlined. More generally, we probably need to add proper support for all CSS at-rules as listed on https://developer.mozilla.org/en-US/docs/Web/CSS/At-rule - adding support for @media is only a special case of that support.

**Comment by jonscottclark** [comment]
Thanks a lot @jrit, I definitely didn't read the docs enough, and ignoring that `<link>` tag will definitely help me out.

As far as not touching `@import`, `@font-face`, etc. when inlining, is it as easy as checking if a property block starts with an `@` or is the support for `preserveMediaQueries` more complex than that?

**Comment by jrit** [comment]
#158 resolved this issue
