### ISSUE TITLE
Options undefined with preserveImportant feat

### ISSUE THREAD

**Issue by arathael** [Automattic/juice#137]
Sympton:
Runtime crashes when using .inlineContent(html, css) with no options. It seems it wont get defaults...
```
TypeError: Cannot read property 'preserveImportant' of undefined
    at addProps (/project/node_modules/juice/lib/juice.js:167:45)
```

**Comment by arathael** [comment]
You can reproduce it with:

```js
var juice = require('juice');
var html = '<p>Hello Bug</p>';
var css = 'p{font-family:"Arial"}';

var output = juice.inlineContent(html, css);
console.log(output);
```

**Comment by jrit** [comment]
Thanks for reporting @arathael - fixed in 1.3.2 which is on npm now

**Comment by arathael** [comment]
Hey thanks man, that was fast. I didn't even have time to bitch about it.

**Comment by jrit** [comment]
Oh, sorry. Maybe next time! :smile:
