### ISSUE TITLE
Juice alters EJS tags

### ISSUE THREAD

**Issue by jerepaajanen** [Automattic/juice#140]
I try to inline css to my .ejs templates. Only problem is that Juice alters ejs tags, making them useless in production. Is there anyway to get around this? 

`<%= config.sitePrefix %>verify?grant=<%= grant._id %>&secret=<%= grant.secret %>
`
becomes

`<%= config.siteprefix="" %="">verify?grant=<%= grant._id="" %="">&secret=<%= grant.secret="" %=""></%=></%=></%=>`

**Comment by jrit** [comment]
@jerepaajanen what version of juice are you using?

**Comment by jerepaajanen** [comment]
Version 1.2.0 and I have tried grunt-inline-css and all the alternatives.
