### ISSUE TITLE
png convert base64

### ISSUE THREAD

**Issue by juanpablocs** [Automattic/juice#151]
as I can make it ignore png files?

help me please

plugins.juice(htmlBuffer, {}, function(err, html){
      if(err) return fn(err);
      file.contents = new Buffer(html);
      fn(null, file);
 });

**Comment by juanpablocs** [comment]
hi I fixed this problem  sending custom option(images:0) to  function web-resources-inliner.

 plugins.juice(htmlBuffer, {webResources:{images:0}}, function(err, html){
                if(err) return fn(err);
                file.contents = new Buffer(html);
                fn(null, file);
            });

**Comment by jrit** [comment]
This is documented behavior here https://github.com/jrit/web-resource-inliner#images-boolean-or-number-default-8
