### ISSUE TITLE
Issue doing toUpperCase() on el.name 

### ISSUE THREAD

**Issue by maghidini** [Automattic/juice#162]
Hello guys I am using email-templates and I don't know why the element " /n " goes to els.
So because "/n" does not have "name" property this cause a TypeError: Cannot read property 'toUpperCase' of undefined on line 138:      

 if (juice.nonVisualElements.indexOf(el.name.toUpperCase()) >= 0) { 

So in order to avoid that, I just recommend to check that before do the toUpperCase() adding this line previously:

if (!el.name) { return } 

What do you think? 
Thanks in advance!

**Comment by maximilianredt** [comment]
This problem still exists in the functions setDimensionAttrs() and setAttributesOnTableElements(). Could use the same fix.
