### ISSUE TITLE
Using 'preserveMediaQueries' with 'juice.inlineDocument'

### ISSUE THREAD

**Issue by t-kelly** [Automattic/juice#173]
I have media queries in the css I am passing to `juice.inlineDocument`. Should `preserveMediaQueries` insert those media queries into the HTML doc the same way `juice.juiceResources` does when you have media queries inside a linked document, ie. `<link rel="stylesheet" href="style.css">`?

I can submit a PR if you guys agree with this.

**Comment by jrit** [comment]
I feel like that would make sense if it isn't currently happening. As long as the media queries are applied in the same ordering as the CSS is applied with inlineDocument, that should provide for consistent behavior. A PR to that effect would be most welcome, please make any needed updates to the readme and provide test coverage if you do open a PR. Thanks!

**Comment by jrit** [comment]
I believe this was resolved by #189
