### ISSUE TITLE
<meta/> is converted to <meta>

### ISSUE THREAD

**Issue by donflopez** [Automattic/juice#184]
The self-closed meta tags are being converted to an only open meta tag, this is problematics, because the 

````
var parser = new DOMParser();
     packageXml = parser.parseFromString(packageText,'text/xml');
````

can't parse the generated doc, maybe is cheerio.

Thank you!

**Comment by jrit** [comment]
Have you tried using the `xmlMode` option of Juice?

**Comment by donflopez** [comment]
Ouch! I didn't see these option, sorry!

Thank you!
