### ISSUE TITLE
Preserve media-queries provided via extraCss

### ISSUE THREAD

**Issue by thasmo** [Automattic/juice#188]
When using `extraCss` to provide CSS with media-queries those won't be inlined i.e. preserved at all. Is there a way to somehow preserve media-queries provided via `extraCss`?

**Comment by jrit** [comment]
I agree this behavior isn't what someone would expect to happen and we should make it work like you expected. `extraCss` has a certain priority level that should just need to be matched by inserting a `<style>` tag in the right place in `<head>`.

**Comment by thasmo** [comment]
Awesome! It would be nice to configure where the `extraCss` will be inserted, maybe the default position could be in the `<head/>` as the last element. In addition if there's no `<head/>` element, it would be useful to configure if the `extraCss` should be inserted at all.
