### ISSUE TITLE
[2.0] Modify option defaults

### ISSUE THREAD

**Issue by jrit** [Automattic/juice#190]
A lot of options have been added for good reasons, but in order to keep backward compatibility in 1.x, too many of them are defaulted to off now. Here are the changes I think would more commonly generate the correct HTML in the most use cases:

- preserveMediaQueries, change `false` to `true`
- preserveFontFaces, change `false` to `true`
- insertPreservedExtraCss, change `false` to `true`
- applyWidthAttributes, change `false` to `true`
- applyHeightAttributes, change `false` to `true`
- applyAttributesTableElements, change `false` to `true`

The only data I have to back up what the defaults should be is my own use and looking at what is depending on Juice on npm, which seems to be mostly email inliners, so feedback is definitely appreciated.

**Comment by custa1200** [comment]
Mkes sense to me. My use case for juice is email, all of those options being what I would want in a world of responsive, rich emails.
