### ISSUE TITLE
Error when using data-inline

### ISSUE THREAD

**Issue by begot** [Automattic/juice#192]
I'm receiving the below error (which doesn't give a lot of information) when trying to use data-inline on a ```<link>``` tag.

    \node_modules\juice\client.js:124
    addProps(utils.parseCSS(cssText)[0][1], utils.styleSelector);
                                       ^

    TypeError: Cannot read property '1' of undefined      

data-inline:

    <link rel="stylesheet" href="link/to/file.css" data-inline />

**Comment by jrit** [comment]
Is it possible for you to attach the CSS file that is being inlined? It is likely there is a syntax error in it, or something that for some reason can't be parsed. On top of that, I agree the error is not very useful, maybe something can be done about that, I'm not remembering what the output of the parser looks like when it chokes at the moment.

**Comment by begot** [comment]
Bizarrely coming back to my code base a week later, I'm now no longer getting the error. 

I can't think of what could have caused this, but all I'm doing is compiling SASS to CSS with node-sass, then inlining it with Juice. So maybe something happened with node-sass rather than Juice.

Thanks for your help!
