### ISSUE TITLE
Flexbox support

### ISSUE THREAD

**Issue by knightcode** [Automattic/juice#193]
I just started using this, so forgive me if I'm just ignorant. These properties seem not to show in the output, despite "display: flex" being allowed:

* flex-direction
* flex-wrap
* flex-flow
* justify-content
* align-items
* align-content
* order
* flex-grow
* flex-shrink
* flex-basis
* flex
* align-self

**Comment by jrit** [comment]
This seems to work in this sample: https://tonicdev.com/5695a77804e6390d00da309b/5695a77804e6390d00da309c

If you can provide an isolated case that reproduces the issue, please post a link to it. Thanks.

**Comment by knightcode** [comment]
ok, it's probably Gmail then. my bad.
