### ISSUE TITLE
A way to have style tags that aren't inlined.

### ISSUE THREAD

**Issue by garrettboatman** [Automattic/juice#194]
Looking for a way to have only a few styles in a style tag that aren't inlined.

Right now, I can wrap them a general media query and use `preserveMediaQueries: true`, but media queries aren't supported in all email clients.

Maybe something like
```
<style data-inline="false">
...
</style>
```

**Comment by jrit** [comment]
Did you try using `data-embed`?

https://github.com/Automattic/juice/blob/e33ec86a21c59f8c50ec3453d613e4f9c12b9ce3/README.md#data-embed

**Comment by garrettboatman** [comment]
Ahh. :facepalm:

Thanks @jrit!
