### ISSUE TITLE
Selector specificity not working for !important rules

### ISSUE THREAD

**Issue by arty-name** [Automattic/juice#204]
When two selectors match the same element, and both have `!important`, then the selector specificity is ignored and the last rule wins: 

```Javascript
juice.inlineContent('<p><a>test', 'p a {color: red!important} a {color: black!important}') 
// '<p><a style="color: black;">test</a></p>'
juice.inlineContent('<p><a>test', 'a {color: black!important} p a {color: red!important}')
// '<p><a style="color: red;">test</a></p>'
```

However for the browsers it’s different. [No matter which rule goes first, if both have !important in them, the more specific wins.](http://embed.plnkr.co/YChmIIhgzanpdgFUeTrK/)

**Comment by jrit** [comment]
Thanks for reporting and including a test case :+1: I agree this looks like a bug.

**Comment by mechanoid** [comment]
\o/

**Comment by arty-name** [comment]
Thank you, @jrit!
