### ISSUE TITLE
No support for vendor prefixed display: flex;

### ISSUE THREAD

**Issue by coloradude** [Automattic/juice#205]
```html
<style>div{display:-ms-flexbox; display: -moz-box; display: -webkit-flex; display: -webkit-box; display: flex;}</style><div></div>
```
results in 

```html
<div style='display: flex;'></div>
```

https://tonicdev.com/coloradude/57054aea6ea4ea1100b4d42b

**Comment by jrit** [comment]
This isn't specific to flex, this is because the CSS is parsed and the last instance of `display` wins when the specificity is the same between all instances. If `display:-ms-flexbox;` happened to be last, then that would win. 

I suggest using https://www.npmjs.com/package/html-postcss after Juice to accomplish your goal.

**Comment by coloradude** [comment]
It seems like this is a case that should be handled by juice itself. In my opinion this goes against the expected behavior. ```display: flex;``` is hardly a fringe use case.

**Comment by jrit** [comment]
@coloradude if you'd like to submit a PR, that would be great. #27 also refers to vendor prefixes, but I think that was for the properties, not the values like this one.

**Comment by coloradude** [comment]
This would be my first open source PR if I can figure out but it would be super cool to do. Ill give it shot!

**Comment by coloradude** [comment]
@jrit I haven't had the time to read through all the source yet but any ideas on where I should be looking?

**Comment by jrit** [comment]
@coloradude I don't have a good short answer to this one. What you'll probably be trying to do is have `parseCSS` give you information on the multiple `display` values in the styles, and then handle those appropriately when inlining.
