### ISSUE TITLE
How don't removing vendor-prefix CSS

### ISSUE THREAD

**Issue by mayr-ink** [Automattic/juice#212]
For example:
My source code has:

```css
display: -webkit-flex;
display: -ms-flexbox;
display: flex;
```

after run juice comand:

```css
display: flex;
```

I need that my compiled code having the three property, someone help me?
My command was:
```sh
juice --preserve-media-queries=true --web-resources-images=true --insert-preserved-extra-css=true --inline-pseudo-elements=true dist/index.html dist/index-inline-resources.html
```

**Comment by jrit** [comment]
please see #205 

I'm going to close this as a duplicate, the other issue will be left open until there is a resolution.
