### ISSUE TITLE
juice.juiceResources is not a function

### ISSUE THREAD

**Issue by generalleger** [Automattic/juice#214]
I am probably missing something simple, but I can get the regular `juice(html)` function to work just fine.  However, when I try to call `juice.juiceResources` I am getting `juice.juiceResources is not a function`

```
    juice.juiceResources(html, options, function(err, html) {
      if(html){
        console.log("ouptut: ", html);
      }
    });
```

Sorry if this is a stupid question. Still new to this.

**Comment by generalleger** [comment]
I think I figured it out.  It is a server only method... which makes sense, of course.

**Comment by rsturim** [comment]
I'm getting the same error.  I'm on 4.2.3 -- what do you mean, "server only".  That's not what the README says.  Can someone explain why `juice.juiceResources is not a function` is returning?  Is there a better example I can see?

**Comment by raamkumaarb** [comment]
I am also getting the same "juice.juiceResources is not a function" :-(. Any fix for this?

**Comment by jrit** [comment]
"server only" meaning that method is available running in Node but not when running in the browser. The browser/client implementation is missing support for getting the remote resources needed for inlining, but if you have an HTML doc with the CSS in style tags, or pass juice the CSS separately via config that all works fine. That is all documented.

That being said, if you have a bug, please provide a full example of what you are doing with code, preferably running online somewhere like runkit so it can be evaluated.
