### ISSUE TITLE
Remove classes and ids when style is applied ?

### ISSUE THREAD

**Issue by iRyusa** [Automattic/juice#225]
Hi there ! 

I'm planning to use Juice in MJML project. We want to introduce a way to inline CSS from `mj-style` see https://github.com/mjmlio/mjml/issues/81

So when my classes and ids are inlined they remain in the final HTML document. I want to know if there's something to remove classes when they're already applied ?

Test example : 
```javascript
it('test removing css class when applied', function() {
  assert.deepEqual(
      juice.inlineContent('<div class="test"></div>', '.test { color: red; }'),
      '<div style="color: red;"></div>');
});
```

**Comment by jrit** [comment]
See https://github.com/Automattic/juice/issues/56
