### ISSUE TITLE
Error with whitespace removal from linear-gradient

### ISSUE THREAD

**Issue by stavro** [Automattic/juice#226]
Version: 2.0.0

Significant whitespace with linear-gradient directions is not preserved during juice inline.

To reproduce:

``` javascript
var juice = require("juice");
var result = juice("<style>div{background-image: linear-gradient(to right, #0099E5, #7C37FF);}</style><div/>");
```

Result:

``` html
<div style="background-image: linear-gradient(toright,#0099E5,#7C37FF);"></div>
```

Expected:

``` html
<div style="background-image: linear-gradient(to right,#0099E5,#7C37FF);"></div>
```

Syntax Spec: https://developer.mozilla.org/en-US/docs/Web/CSS/linear-gradient

**Comment by stavro** [comment]
Not super important, as `to right` can be replaced with `90deg` for the same end result, but I thought I'd share the issue.

**Comment by mechanoid** [comment]
Same problem seems to occur when defining your gradient with steps, like

```
background: linear-gradient(to bottom, rgba(0,0,0,0) 0, rgba(0,0,0,0) 45%, rgba(0,0,0,0.08) 90%, rgba(0,0,0,0) 100%);
```

As a result, the spaces between color and distance is removed too.

```
background: linear-gradient(tobottom,transparent0,transparent45%,rgba(0,0,0,.08) 90%,transparent 100%);
```

**Comment by bago** [comment]
Can you check this with 3.0 release? I didn't test but I guess this could be solved given we replaced the core parser.
