### ISSUE TITLE
git repository dependence

### ISSUE THREAD

**Issue by maxwallasaurus** [Automattic/juice#233]
Hi, 

I would like to use Juice on a work project, but my prod server is erroring due the dependence on mensch. Specifically, because it references the mensch github repository instead of npm (company policy prohibits fetching git repository dependencies). I have requested that they publish the latest release (0.3.3) to npm. If they do so, would it be okay to reflect this change in the juice package.json? 

Thanks for the awesome library. I would love to use it in production!
Cheers, 
Max

**Comment by maxwallasaurus** [comment]
#220

**Comment by jrit** [comment]
Yeah, totally.

**Comment by maxwallasaurus** [comment]
@bago it looks like you are maintaining the github repository for mensch. Do you have access to the npm package, or do you know how to contact the collaborator? If not, it looks like the original author of that package hasn't contributed in years, perhaps a new fork is in order? 

Cheers, 
Max

**Comment by maxwallasaurus** [comment]
@jrit THANK YOU!

**Comment by jrit** [comment]
closing as fixed
