### ISSUE TITLE
Put pseudos into <style> tag

### ISSUE THREAD

**Issue by simontabor** [Automattic/juice#237]
I was under the impression that pseudo selectors would automatically be placed into a `<style>` tag and preserved, just like media queries are. After looking around it seems like this isn't the case.

It feels like an anti-pattern to have to use:

``` css
@media all {
  a:hover {
    color: red;
  }
}
```

to get them to work.

Happy to try to put together a pull request if you think this would be valuable. In any case, I think it should be documented that `ignoredPseudos` will be removed (ignored gives the wrong impression to me).

Cheers!

**Comment by hellocosmin** [comment]
Has this been abandoned? 

It would be extremely useful if `:hover` (and any pseudo in fact) would not need to sit inside a `@media` query. Using this for emails, there are cases where you can't use pseudos inside a media query, but you still need them.

As an aside, I'm also having a particular issue trying to use utility-first CSS (TailwindCSS framework). With that, you can have it generate classes like this: 

```css
.hover-text-dark:hover {
  color: #000000;
}
```

Which make so much sense in markup: `class="text-light hover-text-dark"`

Right now, you can't use those if using Juice, so you need to:

1. Define a breakpoint
2. Specify a prefix for the class name of that breakpoint
3. Use something silly as `.myprefix-hover-text-dark`

Can you please consider preserving any pseudos in Juice, through an option or by changing how `ignoredPseudos` works? (I also found that option name to be confusing). Thanks!

**Comment by hellocosmin** [comment]
Looking at `utils.js`, it would be a simply extra check in the `getPreservedText()` function, to preserve pseudo selectors:

```
(rules[i].selectors && exports.matchesPseudo(rules[i].selectors[0], [':hover', ':active', ':focus', ':visited', ':link'])) ||
```

`matchesPseudo` could be:

```
exports.matchesPseudo = function (needle, haystack) {
  var length = haystack.length || 0;
  for (var i = 0; i < length; i++) {
    if (needle.indexOf(haystack[i]) > -1)
      return true;
  }
  return false;
}
```

Works fine, but looks dirty, and I don't know how to get the `juiceClient.ignoredPseudos` there (so they're not hard coded).

Any thoughts? Would you accept a PR that at least starts with this?

**Comment by jrit** [comment]
You can pass the array from juiceClient.ignoredPseudos into utils either as an argument/option to the existing functions being called or you could define a new getter/setter on utils to handle that.

If you want to put together a PR with tests I feel like what you are suggesting makes sense.

Regarding `ignoredPseudos` as a name. It seems to be confusing already. If you want to maybe add an option called `preservedPseudos` or something like that and document it, I feel like that would be a good idea. Then we can leave alone `ignoredPseudos` and avoid a breaking, and also confusing, change.

Sound good?

**Comment by hellocosmin** [comment]
Sounds great, Jarrett :)

I'm a bit busy this week, but will start working on this as soon as possible. Thanks for the direction/advice as well 👍

**Comment by hellocosmin** [comment]
Since #314 adds a `preservePseudos` option that fixes this, I guess this issue can be closed?
