### ISSUE TITLE
Media queries in css not showing in result using preserveMediaQueries option

### ISSUE THREAD

**Issue by tomyo** [Automattic/juice#241]
Hi, I can't get to make `juice.inlineContent(html, css)` to put the media queries from css argument in a <style> tag in the returned html. I tried with `preserveMediaQueries` option, but it only works, when the queries are inside <style> tags already in the html, not in the provided css. Also tried providing the css in the extraCSS field in options, together with `insertPreservedExtraCss`, but nothing gets inlined :(.
¿What am I doing wrong?
Thanks

**Comment by jrit** [comment]
If you can reproduce the issue on Tonic( https://runkit.com/npm/juice ), that would be best. If `preserveMediaQueries` and `insertPreservedExtraCss` are both true, then the extra CSS should get inserted.

**Comment by jrit** [comment]
I'm closing as this seems abandoned, but feel free to reopen if you can provide an isolated test case.

**Comment by wwform** [comment]
I'm aware this is ancient, but I just ran into the same issue. Test case is here: https://runkit.com/embed/kqul95ysqfxj
I worked around this issue by inserting the CSS in the HTML and using plain `juice(html)`.

**Comment by niksy** [comment]
Just run into the same issue. The way I worked around it:

```js
juice(html, {extraCss: css});
```

It would be nice if `juice.inlineContent(html, css);` did the same.
