### ISSUE TITLE
xmlMode and empty block element

### ISSUE THREAD

**Issue by panec** [Automattic/juice#248]
When `xmlMode: true` option is enabled the elements should preserve `/>` which is useful for img, hr, meta elements, but it does not detects what type of element is uses and in case of HTML block element of `div` when it is empty it breaks the code.
From
`<div></div>`
I expect
`<div style="..."></div>`
But I receive
`<div style="..."/>`
which breaks HTML

**Comment by jrit** [comment]
xmlMode is basically just passed through to cheerio, it might be better to look into making the change there since nothing about that object to XML string process is contained in juice's code. https://www.npmjs.com/package/cheerio
