### ISSUE TITLE
cheerio module failed to work in client side (browser)?

### ISSUE THREAD

**Issue by thucnguyen77** [Automattic/juice#252]
Hi,

I tried to use the library in client side using juice/client as instructed here https://www.npmjs.com/package/juice, but not succeeded. The errors I got were about the nested dependencies in the **cheerio** module on various server-side modules such as "os". 

Wondering if this issue has been identified and planned for fixing?

Thanks,
Thuc

**Comment by jrit** [comment]
I can see where there is a reference to `os` in one of the juice files, which I'd like to remove, but I'm not having any trouble making a browserify bundle or running juice in a browser from that bundle. I'm not sure what might be different between what I'm doing and what you are doing. This is the command I ran to make the bundle `browserify client.js -o tmp/bundle.js --standalone juice`

**Comment by jaytaylor** [comment]
@jrit Running your command attempting to use it today, but no longer seems to compile:

## Node.js v8.2.1

`require('./helpers/juice.js');`

Worked as expected in my test.

## Yarn targeting web-browser

Yarn v0.24.6

Didn't work - project no longer compiles.

dependencies:

```(json)
"dependencies": {
  "autoprefixer": "^7.1.2",
  "babel-preset-env": "^1.6.0",
  "babel-preset-stage-0": "^6.24.1",
  "cssnano": "^3.10.0",
  "html-to-react": "^1.2.11",
  "html-webpack-plugin": "^2.29.0",
  "jquery": "^3.2.1",
  "juice": "^4.1.0",
  "material-ui": "^0.18.6",
  "path": "^0.12.7",
  "postcss-cssnext": "^3.0.0",
  "postcss-flexbugs-fixes": "^3.0.0",
  "postcss-import": "^10.0.0",
  "postcss-loader": "^2.0.6",
  "react": "^15.6.1",
  "react-dom": "^15.6.1",
  "react-promise": "^1.1.3",
  "react-router": "^4.1.1",
  "react-router-dom": "^4.1.1",
  "react-scripts": "^1.0.10",
  "react-tap-event-plugin": "^2.0.1",
  "specificity": "0.1.5",
  "sugarss": "^1.0.0",
  "webpack": "^3.2.0",
  "webpack-dev-server": "^2.5.1"
}
```

Steps to reproduce:

1. 
```bash
#!/usr/bin/env bash

git checkout https://github.com/Automattic/juice/issues/252
browserify client.js -o tmp/bundle.js --standalone juice
```

2.
```(javascript)
import React, { Component } from 'react';
import juice from './helpers/juice .js';

export default class extends Component {
  render() {
    var intermediate = juice('<html><body><div class="my-box">this should be a box with a red background.</div></body></html>');
    return <div>{intermediate}</div>;
  }
}
```

3.
```bash
yarn start
```

```(javascript)
Failed to compile.

./src/helpers/juice.js
  Line 1:      'define' is not defined   no-undef
  Line 1:      'define' is not defined   no-undef
  Line 1:      Unexpected use of 'self'  no-restricted-globals
  Line 1:      Unexpected use of 'self'  no-restricted-globals
  Line 3801:   Unexpected use of 'self'  no-restricted-globals
  Line xxxx:  [Above error repeated 59 more times]
```

**Comment by jrit** [comment]
Do you think it would work better if you do something like `import juice from 'juice/client';` instead of bundling first and trying to include that?

**Comment by jaytaylor** [comment]
@jrit Thanks for following up.  I still have more tests to run, but my conclusion from this foray last weekend is:

Yes, I think it actually does work okay just using the standard import.

:)

**Comment by jrit** [comment]
ok, please update if not
