### ISSUE TITLE
Media queries order is reversed

### ISSUE THREAD

**Issue by Silwing** [Automattic/juice#255]
When using media queries in CSS the order of those is relevant for which rule will end up applying. However in utils.js getPreservedText the following for loop reverses the order of media queries:

`for (var i = rules.length - 1; i >= 0; i--) { ... }`

Is there a reason for this? It caused me a bit of an headache until I realized what the issue was.

**Comment by jrit** [comment]
It sounds like the order is creating a bug, so if there is a reason I'd say its not a very good one 😄 

Feel free to open a PR, otherwise it might be a bit before I get around to looking at it.
