### ISSUE TITLE
CSS counters is not supported

### ISSUE THREAD

**Issue by hjue** [Automattic/juice#256]
My Input is 

```
<style>
body {
    counter-reset: section;
}
h2::before {
    counter-increment: section;
    content:counter(section);
}
</style>
<h2> Title 1</h2>
<h2> Title 2</h2>

```

Juice output

![image](https://cloud.githubusercontent.com/assets/1135045/21602899/da41d4c2-d1d3-11e6-9206-f4108971e306.png)

I hope Juice output

```
<h2><span>1</span> Title 1</h2>
<h2><span>2</span> Title 2</h2>
```

**Comment by jrit** [comment]
If someone wants to open a PR to implement counters that would be amazing. Minimally, I'd like to fix the first and last character being cut off and the documentation being unclear that only plain text is supported for `::before` and `::after`.

**Comment by guanpengchn** [comment]
Expecting...

**Comment by mikevoets** [comment]
The first and last character being cut off is still a problem.
