### ISSUE TITLE
Release new version of web-resource-inliner and version bump it in here too 

### ISSUE THREAD

**Issue by niftylettuce** [Automattic/juice#279]

**Comment by niftylettuce** [comment]
@jrit ping?

**Comment by jrit** [comment]
@niftylettuce sounds good, will do that later today

**Comment by jrit** [comment]
released https://github.com/jrit/web-resource-inliner/releases/tag/v4.2.0 and the semver in juice allows for that install already, so no change here

**Comment by niftylettuce** [comment]
@jrit though it'd be super helpful for a version bump so I don't have to tell my users to uninstall and reinstall, and they could just download the new version and be done with it.

**Comment by niftylettuce** [comment]
this is a bug as far as I know and it should have a version bump

**Comment by jrit** [comment]
Are you suggesting WRI should be 5.0.0 instead of 4.2.0?

**Comment by niftylettuce** [comment]
@jrit sorry I meant minor bump in `juice` to `4.1.2` once you set the new version in `juice` of WRI to `4.2.0`
