### ISSUE TITLE
juice.juiceResources is not a function

### ISSUE THREAD

**Issue by antoniogarcez** [Automattic/juice#292]
Hi,

I'm trying to use method juiceResources because, in my HTML, I have a lot of CSS files referenced by link tags. This is my code:

```javascript
juice.juiceResources($('html')[0].outerHTML, { webResources: { images: false, svgs: false, scripts: false } }, function (err, html) {
    console.log(err);
});
```

But, unfortunately does not work and shows this error:

> Uncaught TypeError: juice.juiceResources is not a function

What is happen?

**Comment by jrit** [comment]
This type of question might be more suited to stackoverflow as you don't seem to be reporting an issue per se.
