### ISSUE TITLE
Can't import juice via rollup

### ISSUE THREAD

**Issue by ProLoser** [Automattic/juice#303]
I'm having some difficulty importing juice via rollup for use in a browser application.

I've had errors about unresolved path to `./package` which is when you import the `package.json` file, then I had to add a plugin to parse the json, then I ran into problems with the shebang from `node_modules/datauri/index.js`.

What is the preferred method of digesting this package for rollup and generating a browser-friendly version?

**Comment by grady-lad** [comment]
Also running into issue @ProLoser did you ever find a solution ?

**Comment by inyono** [comment]
Had a similar problem with webpack. Used https://github.com/JavascriptIsMagic/shebang-loader for the specific module, i.e.
```.js
          {
            test: /\.js$/,
            include: path.resolve(__dirname, 'node_modules', 'datauri'),
            use: [require.resolve('shebang-loader')]
          }
```

**Comment by phjardas** [comment]
I'm having the same problem with TypeScript, because `require('./package')` is not a valid TypeScript import. :cry: 

Is there any reason not to use `require('./package.json')`?
