### ISSUE TITLE
CSS @import methods get removed

### ISSUE THREAD

**Issue by badfeather** [Automattic/juice#306]
Some webfont providers, such as Typekit, provide an `@import` statement as a public method for [using a font in an HTML email](https://helpx.adobe.com/typekit/using/html-email.html). These statements, e.g. `@import url(example.css)` get stripped from the `<head>` `<style>` tag, and don't get inlined anywhere. Is there a method to preserve them?

**Comment by jrit** [comment]
If you can take advantage of `removeStyleTags=false` that would be the simplest. There is nothing specific to `@import`
