### ISSUE TITLE
style and link tags not removed

### ISSUE THREAD

**Issue by PierBover** [Automattic/juice#307]
This is the original HTML:
```html
<head>
	<meta charset="utf-8">
	<title></title>
	<link rel="stylesheet" href="./styles.css">
</head>
```

And this is the result:
```html
<head>
	<meta charset="utf-8">
	<title></title>
	<link rel="stylesheet" href="./styles.css">
</head>
```

Same thing with `<style>` tags. The styles are inlined, but the tags are not removed from the result HTML.

```
const options = {
  removeStyleTags: true
};

let result = juice.inlineContent(originalFile, stylesFile, options);
```

Supposedly `removeStyleTags` is `true` by default but I added it to see if it made any difference.

Am I missing something?

**Comment by jrit** [comment]
Please reproduce the issue in a minimal case on runkit https://npm.runkit.com/juice

**Comment by PierBover** [comment]
I tried but there is something wrong with Runkit:

![image](https://user-images.githubusercontent.com/226483/42961943-fa685a0e-8b55-11e8-861d-c7434577605f.png)

So I've made more tests.

When simply doing...
```
let resultHTML = juice(originalHTML);
```
... the `<style>` tags are correctly removed and the CSS is inlined, but the CSS from `<link>` is not inlined and the tag is not removed either.

It seems this problem only occurs when using `juice.inlineContent();`

**Comment by hellocosmin** [comment]
My understanding is that this actually works as intended.

From the [README](https://github.com/Automattic/juice#juiceinlinecontenthtml-css--options):

#### juice.inlineContent(html, css [, options])

This takes html and css and returns new html with the provided css inlined. **It does not look at `<style>` or `<link rel="stylesheet">` elements at all.**

So yes, it inlines the styles, but doesn't touch the tags they're in. Maybe the last sentence in the description there is a bit vague?

**Comment by jrit** [comment]
That is correct @hellocosmin - `inlineContent` would be a way to use juice without web-resource-inliner getting involved. I didn't notice when the issue was opened.

**Comment by mateusgrb** [comment]
The last sentence could definitely be more explicit, I also misunderstood it.
