### ISSUE TITLE
Combine border attributes

### ISSUE THREAD

**Issue by vnxdev** [Automattic/juice#311]
We need to have an option to make a shorthand oneliner for border attribute.

This doesn't work in Outlook and Windows 10 Mail:
```
border: 1px solid transparent;
border-color: #4CAF50;
```

But this one does:
`border: 1px solid #4CAF50;`

Should be a built-in option to enable such kind of transformation.

Clients with compatibility problems: https://www.campaignmonitor.com/css/box-model/border-color/

**Comment by hellocosmin** [comment]
I disagree, this shouldn't be in core. Juice's responsibility is to inline CSS, not to change the way it's written. There are libraries for dealing with such things, maybe give [postcss-merge-longhand](https://www.npmjs.com/package/postcss-merge-longhand) a try.

**Comment by hellocosmin** [comment]
`juice.styleToAttribute` does not change your CSS, it just adds HTML attributes that correspond to certain CSS properties. Those properties aren't altered.

I totally understand the need for this: had to cope with the fact myself, when using Juice in [Maizzle](https://github.com/ThemeMountain/maizzle), where I'm using Tailwind CSS classes (which are not shorthand).

But the purpose of the library is to inline your CSS, not alter its syntax. Yes, Juice is primarily used for emails, but it's not meant _only_ for that (as described in the readme), and such a breaking change could cause issues for others - there could be situations where the user expects the CSS to be inlined exactly as it was written.

**Comment by jrit** [comment]
@vnxdev I agree with @hellocosmin that this isn't a feature that belongs in juice. There are some other tools out there that do that sort of rewriting for emails. But, juice has a focus on compatible inlining, not on rewriting or providing shorthand. My recommendation is to find or write a simple pre-transform or post-transform tool. web-resource-inliner which is a core dependency of juice has an option called `linkTransform` that is designed for this kind of hook.
