### ISSUE TITLE
Support for codeBlocks in command line

### ISSUE THREAD

**Issue by mnorton-ffs** [Automattic/juice#326]
I'm trying to setup Juice as part of a build process and I need to be able to specify codeBlocks for FreeMarker in order to get the templates to be parsed properly. Is there a way to do this that I'm missing, or would this require additional functionality?

**Comment by jrit** [comment]
I think you might want to use `options-file` as an arg from CLI since no, you can't do codeblocks directly on CLI, but it should parse out from `options-file`

**Comment by mnorton-ffs** [comment]
@jrit I tried placing it inside `options-file` and it doesn't seem to work:

```
"codeBlocks": {
        "freeMarkerStart": {
            "start": "<#",
            "end": ">"
        },
        "freeMarkerEnd": {
            "start": "</#",
            "end": ">"
        }
    }
```

**Comment by mnorton-ffs** [comment]
Might be related to https://github.com/Automattic/juice/issues/257?

**Comment by mnorton-ffs** [comment]
I've added a PR to properly support codeBlocks within an `options-file`. https://github.com/Automattic/juice/pull/327
