### ISSUE TITLE
prefers-color-scheme not being inlined

### ISSUE THREAD

**Issue by notflip** [Automattic/juice#391]
I'm using the following code to enable users that have dark mode enabled to see different colors the the email
```
body {
    color: black;
}
@media (prefers-color-scheme: dark) {
    body {
        color: white;
        background: #121212;
    }
}
```

The body background setting is being applied, since that is not being applied in the original body css, but the color setting is not being overwritten, it does get applied when I use `!important`, but it seems bad practice to go around and add important to every selector inside my prefers-color-scheme.

Does anyone know how I can achieve this?

**Comment by jrit** [comment]
yes, you should use important in your media queries. you are writing a media query based on the CSS as it will be after it is inlined, which will mean all the styles are in the style attributes
