### ISSUE TITLE
Is it possible to use with TailwindCSS?

### ISSUE THREAD

**Issue by ospfranco** [Automattic/juice#393]
Hello, I'm really interested in using the package, I can't seem to find a way to make it work with Tailwind however, it seems most people have their css already preprocessed and you can import it somehow, but it's not clear to me how to make it work with Tailwind

Has anyone tried this before?

**Comment by cossssmin** [comment]
Yup, I'm using it in Maizzle:

https://github.com/maizzle/framework

**Comment by ospfranco** [comment]
thanks! I ended up figuring in out how to use pure tailwind and react to render emails
