### ISSUE TITLE
Building failed after cherrio was updated to 1.0.0-rc.11

### ISSUE THREAD

**Issue by DeepVince** [Automattic/juice#402]
The dependency cheerio brought a **breaking change** in [v1.0.0-rc.11](https://github.com/cheeriojs/cheerio/releases/tag/v1.0.0-rc.11)

Juice currently uses version 1.0.0-rc.10 and above, so the latest cheerio version 1.0.0-rc.11 will be installed when `npm install` is executed, causing the project to fail to build. Details can be found in this [issue](https://github.com/cheeriojs/cheerio/issues/2545).

Would you consider releasing a small update to fix cheerio version number below 1.0.0-rc.11?
In this way, the problem is solved after we update to the latest juice version.

I submitted a [pr](https://github.com/Automattic/juice/pull/401) to fix this.

Anyway, thanks for the juice

**Comment by jrit** [comment]
merged and released, hope that helps
