### ISSUE TITLE
Preserve HTML character entity references

### ISSUE THREAD

**Issue by jmeas** [Automattic/juice#43]
Juice doesn't preserve the state of your HTML character entity references when it works with documents. It makes two types of modifications:

1. It will translate some HTML character entity references in the outputted document. For instance, `&ndash;` will be turned into `–` after being passed through juice.

2. It will do the opposite for other characters. For instance, `&` will become `&amp;`.

This behavior might be fine in most cases, but it has a number of consequences. One consequence is that opening the HTML file in a browser will display `â€“` instead of the n dash, to provide example for the 1st type of modification. Further, with my company's email system, sending the email like this will cause the email to be sent with utf-8 encoding instead of ascii, which is what it normally sends as. Independent of whether ascii is a good choice for encoding, or not, the fact that juice affects that is the principle I'm concerned with.

There would be more consistent input-output behavior if the character entity references were untouched by juice.

Edit: Upon looking at the source, this seems like an issue with JSDom. I'll be looking into the issue further there.

**Comment by jrit** [comment]
I confirmed this is resolved and added a test case to prevent regression. Closing.

**Comment by begot** [comment]
Why are apostrophe's always converted to ```&apos;```? Even ```&#39;``` will be converted to ```&apos;```

I can't use ```&apos;``` as its for a HTML email.

Are there any potiental workarounds for this?

**Comment by jrit** [comment]
@begot I'm not which version you are using, but this example shows it working fine: https://tonicdev.com/56a97f108d0e800d0005f565/56a97f108d0e800d0005f566

If you can reproduce the issue, please post a link

**Comment by ahfarmer** [comment]
I was confused by this for a bit. I was using declassify and it will convert `'` to `&apos;`. So no issue in juice, but if you are using declassify right afterwards you'll have this problem.
