### ISSUE TITLE
Improper CSS is ignored; effect cascades (CLI)

### ISSUE THREAD

**Issue by jmeas** [Automattic/juice#44]
Some poorly formatted CSS properties are ignored by juice. But the ignoring cascades, and affects every other property in the stylesheet. Consequently, anything before the poor CSS is inlined as it should be, while everything after the poor CSS is ignored.

Example:

*index.html*

```
<html lang="en">
<head>
  <meta charset="UTF-8">
  <title>Testing</title>
  <link rel="stylesheet" href="style.css">
</head>
<body>
  <table>
    <tr>
      <td><a href="sdf">a test!</a></td>
    </tr>
  </table>
</body>
</html>
```

*style.css*

```
body {
  padding: 5px;
}
a {
  color: ;
}
table {
  padding: 5px;
  color: #333;
}
```

*output.html*

```
<html lang="en">
<head>
  <meta charset="UTF-8" />
  <title>Testing</title>
  
</head>
<body style="padding: 5px;">
  <table>
    <tr>
      <td><a href="sdf" style="color: #333;">a test!</a></td>
    </tr>
  </table>
</body>
</html>
```

The expected result would give `padding: 5px;` and `color: #333` to the table. And it will do this if you remove `color: ;` from the stylesheet.

I would expect `color: ;` to be ignored and the rest of the stylesheet to be processed as usual.

**Comment by stevenvachon** [comment]
use [postcss-safe-parser](https://www.npmjs.com/package/postcss-safe-parser)

**Comment by bago** [comment]
I wrote a test-case so to prove that moving to a different css parser will fix the issue.
See #215
