### ISSUE TITLE
CSS wildcard affects subsequent single-property selectors

### ISSUE THREAD

**Issue by jklegseth** [Automattic/juice#48]
CSS wildcards such as `* { margin:0; padding:0; }` are very common in HTML email CSS, often as the first ruleset. I noticed a strange behavior today. For this test I used an HTML page with a single tag

````
<h1>The Leading Source for Private Mortgages</h1>
````

And this CSS in a linked stylesheet:

````
* { padding: 0; }
h1 { padding-top: 10px; }
h1 { padding: 0; }
````

I expected the finally `h1` to result in no padding but instead the inline style was:

````
style="padding: 0; padding-top: 10px;"
````

If I remove the wildcard selector:

````
h1 { padding-top: 10px; }
h1 { padding: 0; }
````

I get the expected result:

````
style="padding-top: 10px; border: 0;"
````

So the wildcard seems to be the problem. I also noticed that if I return to the original CSS and use the shorthand `padding` instead of `padding-top` in the `h1` selector:

````
* { padding: 0; }
h1 { padding: 10px 0 0 0; }
h1 { padding: 0; }
````

It now cascades correctly and is the cleanest:

````
style="padding: 0;"
````

The solution for now seems to be to use shorthand properties, i.e., `padding` instead of `padding-top`. One other test I did was to see what happened if I listed each property as a separate declaration:

````
* { padding: 0; }
h1 { padding-top: 10px; padding-left: 0; padding-right: 0; padding-bottom: 0; }
h1 { padding: 0; }
````

This also failed to cascade properly:

````
style="padding: 0; padding-top: 10px; padding-left: 0; padding-right: 0; padding-bottom: 0;"
````

**Comment by jrit** [comment]
@parshap indicated this was resolved by #96 so closing
