### ISSUE TITLE
Repository field is missing

### ISSUE THREAD

**Issue by binarykitchen** [Automattic/juice#50]
When `npm install`-ing juice, I see this warning:

```
npm WARN package.json juice@0.4.0 No repository field.
```

**Comment by Andersos** [comment]
Repository field was added in https://github.com/Automattic/juice/commit/55eae09c5c76392d4ff242d75a2164df7d516811 maybe this can be closed

**Comment by jrit** [comment]
Thanks @Andersos - it was later updated to `https://github.com/Automattic/juice.git` as well, so is current
