### ISSUE TITLE
Unbale to install through the Node.js Tools for Visual Studio packae manager 

### ISSUE THREAD

**Issue by custa1200** [Automattic/juice#54]
I am having trouble installing the juice package using the Node.js Tools for Visual Studio package manager. It fails to install with the following console output:

====Executing command 'npm install juice --save-dev '====

npm http GET https://registry.npmjs.org/juice
npm http 304 https://registry.npmjs.org/juice
npm http GET https://registry.npmjs.org/cssom
npm http GET https://registry.npmjs.org/batch
npm http GET https://registry.npmjs.org/superagent
npm http GET https://registry.npmjs.org/jsdom
npm http GET https://registry.npmjs.org/commander
npm http GET https://registry.npmjs.org/slick
npm http 304 https://registry.npmjs.org/superagent
npm http 304 https://registry.npmjs.org/cssom
npm http 304 https://registry.npmjs.org/commander
npm http 304 https://registry.npmjs.org/jsdom
npm http 304 https://registry.npmjs.org/batch
npm http 304 https://registry.npmjs.org/slick
npm http GET https://registry.npmjs.org/keypress
npm http GET https://registry.npmjs.org/qs/0.6.5
npm http GET https://registry.npmjs.org/formidable/1.0.9
npm http GET https://registry.npmjs.org/emitter-component/1.0.0
npm http GET https://registry.npmjs.org/methods/0.0.1
npm http GET https://registry.npmjs.org/mime/1.2.5
npm http GET https://registry.npmjs.org/cookiejar/1.3.0
npm http GET https://registry.npmjs.org/debug
npm http GET https://registry.npmjs.org/nwmatcher
npm http GET https://registry.npmjs.org/cssstyle
npm http GET https://registry.npmjs.org/htmlparser2
npm http GET https://registry.npmjs.org/contextify
npm http GET https://registry.npmjs.org/request
npm http 304 https://registry.npmjs.org/keypress
npm http 304 https://registry.npmjs.org/formidable/1.0.9
npm http 304 https://registry.npmjs.org/debug
npm http 304 https://registry.npmjs.org/qs/0.6.5
npm http 304 https://registry.npmjs.org/cssstyle
npm http 304 https://registry.npmjs.org/request
npm http 304 https://registry.npmjs.org/methods/0.0.1
npm http 304 https://registry.npmjs.org/nwmatcher
npm http 304 https://registry.npmjs.org/contextify
npm http 304 https://registry.npmjs.org/emitter-component/1.0.0
npm http 304 https://registry.npmjs.org/cookiejar/1.3.0
npm http 304 https://registry.npmjs.org/mime/1.2.5
npm http 304 https://registry.npmjs.org/htmlparser2
npm http GET https://registry.npmjs.org/bindings
npm http GET https://registry.npmjs.org/node-uuid
npm http GET https://registry.npmjs.org/json-stringify-safe
npm http GET https://registry.npmjs.org/qs
npm http GET https://registry.npmjs.org/forever-agent
npm http GET https://registry.npmjs.org/tough-cookie
npm http GET https://registry.npmjs.org/form-data
npm http GET https://registry.npmjs.org/mime
npm http GET https://registry.npmjs.org/http-signature
npm http GET https://registry.npmjs.org/tunnel-agent
npm http GET https://registry.npmjs.org/oauth-sign
npm http GET https://registry.npmjs.org/aws-sign2
npm http GET https://registry.npmjs.org/hawk
npm http GET https://registry.npmjs.org/domhandler
npm http GET https://registry.npmjs.org/domutils
npm http GET https://registry.npmjs.org/domelementtype
npm http GET https://registry.npmjs.org/readable-stream
npm http 304 https://registry.npmjs.org/node-uuid
npm http 304 https://registry.npmjs.org/readable-stream
npm http 304 https://registry.npmjs.org/qs
npm http 304 https://registry.npmjs.org/bindings
npm http 304 https://registry.npmjs.org/http-signature
npm http 304 https://registry.npmjs.org/forever-agent
npm http 304 https://registry.npmjs.org/json-stringify-safe
npm http 304 https://registry.npmjs.org/oauth-sign
npm http 304 https://registry.npmjs.org/mime
npm http 304 https://registry.npmjs.org/tough-cookie
npm http 304 https://registry.npmjs.org/form-data
npm http 304 https://registry.npmjs.org/tunnel-agent
npm http 304 https://registry.npmjs.org/hawk

> contextify@0.1.6 install D:\Projects\ModernMail\ModernMail\node_modules\juice\node_modules\jsdom\node_modules\contextify
> node-gyp rebuild

D:\Projects\ModernMail\ModernMail\node_modules\juice\node_modules\jsdom\node_modules\contextify>node "C:\Program Files\nodejs\node_modules\npm\bin\node-gyp-bin\\..\..\node_modules\node-gyp\bin\node-gyp.js" rebuild 
gypnpm http 304 https://registry.npmjs.org/aws-sign2
npm http 304 https://registry.npmjs.org/domelementtype
npm http 304 https://registry.npmjs.org/domutils
npm http 304 https://registry.npmjs.org/domhandler
npm http GET https://registry.npmjs.org/combined-stream
npm http GET https://registry.npmjs.org/async
npm http GET https://registry.npmjs.org/assert-plus/0.1.2
npm http GET https://registry.npmjs.org/asn1/0.1.11
npm http GET https://registry.npmjs.org/ctype/0.5.2
npm ERR! Error: ENOENT, lstat 'D:\Projects\ModernMail\ModernMail\node_modules\juice\node_modules\jsdom\node_modules\htmlparser2\node_modules\readable-stream\float.patch'
npm ERR! If you need help, you may report this *entire* log,
npm ERR! including the npm and node versions, at:
npm ERR!     <http://github.com/isaacs/npm/issues>

npm ERR! System Windows_NT 6.1.7601
npm ERR! command "C:\\Program Files\\nodejs\\\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install" "juice" "--save-dev"
npm ERR! cwd D:\Projects\ModernMail\ModernMail
npm ERR! node -v v0.10.25
npm ERR! npm -v 1.3.24
npm ERR! path D:\Projects\ModernMail\ModernMail\node_modules\juice\node_modules\jsdom\node_modules\htmlparser2\node_modules\readable-stream\float.patch
npm ERR! fstream_path D:\Projects\ModernMail\ModernMail\node_modules\juice\node_modules\jsdom\node_modules\htmlparser2\node_modules\readable-stream\float.patch
npm ERR! fstream_type File
npm ERR! fstream_class FileWriter
npm ERR! code ENOENT
npm ERR! errno 34
npm ERR! fstream_stack C:\Program Files\nodejs\node_modules\npm\node_modules\fstream\lib\writer.js:284:26
npm ERR! fstream_stack Object.oncomplete (fs.js:107:15)
npm ERR! Error: ENOENT, lstat 'D:\Projects\ModernMail\ModernMail\node_modules\juice\node_modules\jsdom\node_modules\htmlparser2\node_modules\domhandler\test\cases\13-comment_in_text.json'
npm ERR! If you need help, you may report this *entire* log,
npm ERR! including the npm and node versions, at:
npm ERR!     <http://github.com/isaacs/npm/issues>

npm ERR! System Windows_NT 6.1.7601
npm ERR! command "C:\\Program Files\\nodejs\\\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install" "juice" "--save-dev"
npm ERR! cwd D:\Projects\ModernMail\ModernMail
npm ERR! node -v v0.10.25
npm ERR! npm -v 1.3.24
npm ERR! path D:\Projects\ModernMail\ModernMail\node_modules\juice\node_modules\jsdom\node_modules\htmlparser2\node_modules\domhandler\test\cases\13-comment_in_text.json
npm ERR! fstream_path D:\Projects\ModernMail\ModernMail\node_modules\juice\node_modules\jsdom\node_modules\htmlparser2\node_modules\domhandler\test\cases\13-comment_in_text.json
npm ERR! fstream_type File
npm ERR! fstream_class FileWriter
npm ERR! code ENOENT
npm ERR! errno 34
npm ERR! fstream_stack C:\Program Files\nodejs\node_modules\npm\node_modules\fstream\lib\writer.js:284:26
npm ERR! fstream_stack Object.oncomplete (fs.js:107:15)
npm ERR! Error: ENOENT, lstat 'D:\Projects\ModernMail\ModernMail\node_modules\juice\node_modules\jsdom\node_modules\request\node_modules\hawk\images\logo.png'
npm ERR! If you need help, you may report this *entire* log,
npm ERR! including the npm and node versions, at:
npm ERR!     <http://github.com/isaacs/npm/issues>

npm ERR! System Windows_NT 6.1.7601
npm ERR! command "C:\\Program Files\\nodejs\\\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install" "juice" "--save-dev"
npm ERR! cwd D:\Projects\ModernMail\ModernMail
npm ERR! node -v v0.10.25
npm ERR! npm -v 1.3.24
npm ERR! path D:\Projects\ModernMail\ModernMail\node_modules\juice\node_modules\jsdom\node_modules\request\node_modules\hawk\images\logo.png
npm ERR! fstream_path D:\Projects\ModernMail\ModernMail\node_modules\juice\node_modules\jsdom\node_modules\request\node_modules\hawk\images\logo.png
npm ERR! fstream_type File
npm ERR! fstream_class FileWriter
npm ERR! code ENOENT
npm ERR! errno 34
npm ERR! fstream_stack C:\Program Files\nodejs\node_modules\npm\node_modules\fstream\lib\writer.js:284:26
npm ERR! fstream_stack Object.oncomplete (fs.js:107:15)
npm ERR! Error: ENOENT, lstat 'D:\Projects\ModernMail\ModernMail\node_modules\juice\node_modules\jsdom\node_modules\request\node_modules\tough-cookie\lib\cookie.js'
npm ERR! If you need help, you may report this *entire* log,
npm ERR! including the npm and node versions, at:
npm ERR!     <http://github.com/isaacs/npm/issues>

npm ERR! System Windows_NT 6.1.7601
npm ERR! command "C:\\Program Files\\nodejs\\\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install" "juice" "--save-dev"
npm ERR! cwd D:\Projects\ModernMail\ModernMail
npm ERR! node -v v0.10.25
npm ERR! npm -v 1.3.24
npm ERR! path D:\Projects\ModernMail\ModernMail\node_modules\juice\node_modules\jsdom\node_modules\request\node_modules\tough-cookie\lib\cookie.js
npm ERR! fstream_path D:\Projects\ModernMail\ModernMail\node_modules\juice\node_modules\jsdom\node_modules\request\node_modules\tough-cookie\lib\cookie.js
npm ERR! fstream_type File
npm ERR! fstream_class FileWriter
npm ERR! code ENOENT
npm ERR! errno 34
npm ERR! fstream_stack C:\Program Files\nodejs\node_modules\npm\node_modules\fstream\lib\writer.js:284:26
npm ERR! fstream_stack Object.oncomplete (fs.js:107:15)
npm ERR! contextify@0.1.6 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the contextify@0.1.6 install script.
npm ERR! This is most likely a problem with the contextify package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get their info via:
npm ERR!     npm owner ls contextify
npm ERR! There is likely additional logging output above.

npm ERR! System Windows_NT 6.1.7601
npm ERR! command "C:\\Program Files\\nodejs\\\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install" "juice" "--save-dev"
npm ERR! cwd D:\Projects\ModernMail\ModernMail
npm ERR! node -v v0.10.25
npm ERR! npm -v 1.3.24
npm ERR! code ELIFECYCLE
npm http 304 https://registry.npmjs.org/combined-stream
npm http 304 https://registry.npmjs.org/async
npm http GET https://registry.npmjs.org/delayed-stream/0.0.5
npm http 304 https://registry.npmjs.org/asn1/0.1.11
npm http 304 https://registry.npmjs.org/assert-plus/0.1.2
npm http 304 https://registry.npmjs.org/ctype/0.5.2
npm http 304 https://registry.npmjs.org/delayed-stream/0.0.5
npm

====npm command completed with exit code 34====

**Comment by Andersos** [comment]
Is this still a problem you are having after version 1?
Can you try on the latest version of this project?

**Comment by jrit** [comment]
The stack shows node-gyp failing during the jsdom install. There are no longer any native modules included since jsdom was removed, so the root cause of this issue is fixed.
