### ISSUE TITLE
unable to handle media queriers

### ISSUE THREAD

**Issue by loranbriggs** [Automattic/juice#55]
Great plugin BTW, but when I am trying to inline a mobile friendly email, the defaults just throw away the media queries. I know I have the option of not deleting them, but it would be nice to only delete the ones that got applied.

I guess an alternative would be to internal CSS (head style block) the media query's and external everything else and remove just the external ones.

Thanks!

**Comment by jrit** [comment]
Media query support has been available since `preserveMediaQueries` was added as an option.
