### ISSUE TITLE
[suggestion]: Helper to remove the classes from HTML tags

### ISSUE THREAD

**Issue by kumarharsh** [Automattic/juice#56]
Is there a way to remove the classes on the tags once the styles are inlined?
I'd wish to have this feature so that the e-mail size is reduced, because the classes would be unnecessary anyways if the styles are inlined.

**Comment by TheHanna** [comment]
+1

For now, I'm utilizing [grunt-unclassify](https://github.com/mariusc23/grunt-unclassify) to accomplish this.

**Comment by jrit** [comment]
You can use https://www.npmjs.com/package/declassify now to remove classes and ids that are no longer needed. It is somewhat more targeted to post-processing Juice than grunt-unclassify, not to discourage anyone from using it, it looks good too.
