### ISSUE TITLE
It would be nice to at least mention external dependencies

### ISSUE THREAD

**Issue by tunderdomb** [Automattic/juice#58]
like python. 

https://github.com/TooTallNate/node-gyp

    node-gyp rebuild
    ...
    gyp ERR! configure error
    gyp ERR! stack Error: Can't find Python executable "python", you can set the PYTHON    env variable.
    gyp ERR! stack     at failNoPython...

edit: I'm not even going to try to find out what of your dependency's dependency gyp is. Please notify the users about such things. Don't expect everyone to have the same environment as you.

**Comment by jrit** [comment]
jsdom was removed for v1.0 so there are no longer any native modules, that seems to be the root issue here, so I'm going to close this one.
