### ISSUE TITLE
Disable rewriting of language or template specific parts.

### ISSUE THREAD

**Issue by Jaspur** [Automattic/juice#60]
At the moment the following isn't working, when you make use of TemplateParsers:
```
// from
<p>Dear {{ $person->user->firstname }},</p>
// to
<p>Dear {{ $person-&gt;user-&gt;firstname }},</p>
```

And the following code is also incorrect parsed:
```
// from
<?php
$demo = Demo::whereEmail($email)->first();
?>
// to
first();
?&gt;
```

**Comment by jrit** [comment]
This should be resolved, there are some very similar test cases in place to prevent regression. Closing.
