### ISSUE TITLE
npm install fails on Windows8.1 x64

### ISSUE THREAD

**Issue by leibale** [Automattic/juice#69]
We're getting the following error:

C:\Program Files (x86)\MSBuild\Microsoft.Cpp\v4.0\Microsoft.Cpp.InvalidPlatform
.Targets(23,7): error MSB8007: The Platform for project 'contextify.vcxproj' is
 invalid.  Platform='x64'. You may be seeing this message because you are tryin
g to build a project without a solution file, and have specified a non-default
Platform that doesn't exist for this project. [C:\Users\yossi\node_modules\juic
e\node_modules\jsdom\node_modules\contextify\build\contextify.vcxproj]

**Comment by Andersos** [comment]
Why did you close the issue @leibale ? Did you get it to work?

**Comment by leibale** [comment]
i changed the system to linux before long time, i have no way to help

**Comment by jrit** [comment]
If I remember right, this was an issue that was related to jsdom having a dependency on contextify, which had some issues building during npm install. So it should be resolved based on contextify no longer being a dependency of juice since jsdom was replaced with cheerio.
