### ISSUE TITLE
Error thrown in juiceContent() is not an instance of Error

### ISSUE THREAD

**Issue by binarykitchen** [Automattic/juice#71]
... but a plain string, in my case simply for example `8: ")" not found`.

I expect it to be an instance of error with all it's features like stack etc.

**Comment by jrit** [comment]
@binarykitchen I'm not sure where this error is coming from, it might just be bubbling up from a dependency. If you can post a sample that can reproduce the error, it could potentially be patched in juice or in the relevant dependency.

**Comment by binarykitchen** [comment]
i cannot remember, this ticket is almost one year old ...
