### ISSUE TITLE
Problem with 'filter' property

### ISSUE THREAD

**Issue by balek** [Automattic/juice#74]
juice fails with `Error: Unmatched '` for this style:
`filter: progidDXImageTransform.Microsoft.gradient(startColorstr='argb(rgba(0,0,0,0.5))', endColorstr='argb(rgba(0,0,0,0))', GradientType=1)`

I can't use bootstrap (actually bootstrap-stylus) with juice because of this bug.

**Comment by jrit** [comment]
This error originates in https://github.com/NV/CSSOM - a patch would need to be made there.

**Comment by bago** [comment]
As part of replacing CSSOM with mensch (#215) I added a test case for  this issue and I confirm moving to mensch will fix this.
