### ISSUE TITLE
jsdom too slow

### ISSUE THREAD

**Issue by Philmod** [Automattic/juice#80]
Hey guys,

We had to move away from juice, because jsdom is taking more than 5 minutes to parse long html (1Mb).

I found a solution using cheerio which is way faster.

Tell me if you need more information about it.

Best,
Philmod

**Comment by jrit** [comment]
jsdom has been replaced with cheerio in v1.0.0 - I'd be interested to know how you see this impacting performance in your usage. Hopefully there is the improvement you'd expect.

**Comment by Philmod** [comment]
+1
