### ISSUE TITLE
juice should not change my <br> to <br /> 

### ISSUE THREAD

**Issue by jng5** [Automattic/juice#82]
My code uses `<br>` html syntax, which for some reason gets changed to `<br />`.

Can we remove this behavior? Given that it is a CSS inliner, it really shouldn't touch other parts of my DOM.

**Comment by gunnx** [comment]
+1

**Comment by jrit** [comment]
This is actually already fixed since 1.0, but I'll add a test case, since I couldn't actually find one and we need the counter-case for #122
