### ISSUE TITLE
Prepend to inline style instead of postpend

### ISSUE THREAD

**Issue by Jehanzeb-Malik** [Automattic/juice#86]
Hi

I am using juiceContent. For me juice is appending the styles from stylesheet at the end of the already there inline styles. This gives the preference to the styles from stylesheet, whereas preference should be given to inline styles.

For example:
This is my markup
`<p style="margin-left: 20px;">Juice</p>`

This is stylesheet
`p {`
    `margin: 0px;`
`}`

Applying juice makes it:
`<p style="margin-left: 20px; margin:0px">Juice</p>`

Now that the `margin: 0px` is appended at the end, it takes preference in style. Inline styles should maintain the priority after juice.

**Comment by parshap** [comment]
This is because *juice* currently sorts properties alphabetically. I've changed this so that properties are sorted by specificity, also taking into account inline styles. This change is proposed in #96.

**Comment by jrit** [comment]
I think @parshap fixed the underlying issue here, so closing
