### ISSUE TITLE
split extracted style tag into js object

### ISSUE THREAD

**Issue by DinisCruz** [Automattic/juice#88]
Hi, I'm using juice with cheerio to write unit tests and was wondering if you had an API in juice to parse the generated style tags.

Basically going from 

```
background: url(../assets/logos/logos.jpg) no-repeat; background-position: 0px -50px; height: 50px; width: 250px; margin: 0 auto;
```

to 

```
{ background: 'url(../assets/logos/logos.jpg) no-repeat',
 'background-position': '0px -50px',
  height: '50px',
  width: '250px',
  margin: '0 auto' }
```

more details in this question http://stackoverflow.com/questions/27753942/create-object-from-string-in-coffee-script

**Comment by parshap** [comment]
Juice does not provide this kind of API. Your best bet would be to use something like *[css][]* to parse out the data you need.

[css]: https://www.npmjs.com/package/css

**Comment by jrit** [comment]
Closing this issue as the answer above seems correct to me and this was more a question than an actual issue.
