### ISSUE TITLE
Disable rewriting of language or template specific parts.

### ISSUE THREAD

**Issue by kaiserkoenig** [Automattic/juice#89]
Hi,

we want to use gulp-inline-css to put css into our mail templates.
But there is a big problem with your implementation, as you can see here:
https://github.com/jonkemp/gulp-inline-css

is there any possibility to make jsdom OPTIONAL?

thanks and a happy new year.

Timo

**Comment by LekeFly** [comment]
Did you find a workaround for this? @kaiserkoenig

**Comment by parshap** [comment]
> we want to use gulp-inline-css to put css into our mail templates.
But there is a big problem with your implementation, as you can see here:
https://github.com/jonkemp/gulp-inline-css

What is the problem exactly? Your link just links to to the github repo with no further details.

jsdom cannot be easily made optional.

**Comment by kaiserkoenig** [comment]
as described in the issue ( https://github.com/jonkemp/gulp-inline-css/issues/4 ) there is a problem with template specific parts, like html characters. the developer there says he can't do anything, so i'm writing here. maybe there's a solution he and you can talk about.

thx

**Comment by jrit** [comment]
@kaiserkoenig v1.0.0 should resolve these issues. I just added some test cases using the examples in jonkemp/gulp-inline-css#4 that passed without any issue.

**Comment by jrit** [comment]
There are some test cases now that cover almost exactly what is in jonkemp/gulp-inline-css#4 so I'm going to close this as resolved
