### ISSUE TITLE
Status of project

### ISSUE THREAD

**Issue by parshap** [Automattic/juice#90]
What is the status of this project? How does it compare to the [juice2][] fork? It looks like many of the changes in juice2 made it back upstream into juice recently.

There are changes on master that haven't been published to npm. Master fixes some issues I've noticed with specificity on 0.5.0. Are there any plans to publish a new version to npm?

[juice2]: https://github.com/andrewrk/juice

**Comment by jrit** [comment]
This fork is almost entirely in sync with juice2 currently but a release was never published by @thomasguillot after the last few commits, so the release version of this fork is not up to date. I'm working to disentangle some dependencies related to pulling in external resources before they are "juiced" at the moment.

**Comment by jrit** [comment]
@parshap think this can be closed, though I just realized I tagged the wrong person... oops.
