### ISSUE TITLE
Upgrading to node 0.12.0

### ISSUE THREAD

**Issue by silintzir** [Automattic/juice#99]
I am having this error after updating to node 0.12.0 when using the example on the juice guide

TypeError: Cannot read property 'removeChild' of null
    at getStylesData (/Volumes/www/impleo/common/node_modules/juice/lib/juice.js:250:57)

Setting removeStyleTags to false, solves the problem but then css is not inlined in the output.

**Comment by felipefdl** [comment]
Has the same problem with IO.js 1.1.0.

**Comment by parshap** [comment]
The problem is with a very old version of *jsdom* that juice depends on. @jrit mentioned he has a patch that rips out jsdom in favor of cheerio, which fixes 0.12 support. @jrit could you submit a PR for that?
